### ISSUE TITLE
JRE 8: 32-bit and 64-bit overwrite each others cached installer

### ISSUE THREAD

**Issue by jstuyts** [proudcanadianeh/ChocoPackages#19]
I reinstall my system regularly. To reduce the time it takes I use a Chocolatey cache that can be reused for reinstalls. The problem is that the 32- and 64-bit JRE 8 installations keep overwriting each others cached installers. Because of this I have to redownload 130 MB every reinstall.

Here is what happens during a reinstall:
* The 32-bit version installation sees that a file exists in the cache, and checks the hashes.
* The hashes do not match because it is the 64-bit version from the previous install, so the 32-bit version is downloaded, overwriting the 64-bit version that already exists in the cache.
* The 32-bit version is installed.
* The 64-bit version installation sees that a file exists in the cache, and checks the hashes.
* The hashes do not match because it is the just downloaded 32-bit version, so the 64-bit version is downloaded, overwriting the 32-bit version that already exists in the cache.
* The 64-bit version is installed.

I don't know if this is a limitiation of Chocolatey, and I have almost no knowledge about Chocolatey, but I think this is because the same package name is used for `Install-ChocolateyPackage` for both versions in `/chocolateyInstall.ps1`.

**Comment by proudcanadianeh** [comment]
I unfortunately am not sure what I could do about this besides splitting it into two packages in chocolatey, and I dont know if the demand is there to justify it :(

**Comment by proudcanadianeh** [comment]
Ok, it took me a day to make it work but with the help from the Chocolatey team I have it fixed!
