### ISSUE TITLE
Java SE Runtime Environment Package Issue

### ISSUE THREAD

**Issue by Rgum00** [proudcanadianeh/ChocoPackages#2]
Having an issue I discovered recently where when running Chocolatey as system to install to the latest version of JRE8 it doesn't actually install the program. But Chocolatey reports the latest version is indeed installed.

![2016-10-21_10-46-05](https://cloud.githubusercontent.com/assets/23055250/19688439/bcba3afc-9a97-11e6-90d6-44906444ee1a.jpg)

**Comment by proudcanadianeh** [comment]
I have seen this, unfortunately I dont have a solution for it. The script works perfectly when running normally, but just fails when running unattended as system. I am wondering if it is an issue with the Java installer, but if so that means there is nothing I could do about it :(

**Comment by Rgum00** [comment]
I figured that would be the verdict! I did some testing and like you said as soon as I run it as a user and not system it installs perfectly.

**Comment by stefanfritsch** [comment]
I have the same issue while running on a system interactively.

Powershell as admin, choco install -y jre8, and nothing gets installed.

**Comment by proudcanadianeh** [comment]
Going to close this issue due to its age and since running non-interactively as system is something that unfortunately just doesn't seem to work with the installer.
