### ISSUE TITLE
(jre8) JAVA_HOME doesn't get updated

### ISSUE THREAD

**Issue by bcurran3** [proudcanadianeh/ChocoPackages#23]
I have this constant problem that when Java gets updated the JAVA_HOME environment variable doesn't get updated to reflect the latest installed version. It breaks all my programs that require JAVA_HOME to find the java.exe executable after removing old versions.

I've brought this up before, but maybe in the wrong repository since I don't see an issue by me here.

Here's an example of how outdated my JAVA_HOME environmental variable is on the machine I'm using at the moment:

> PS C:\Program Files\Java\jre1.8.0_192\bin> write-host $env:JAVA_HOME
> C:\Program Files\Java\jre1.8.0_152
> PS C:\Program Files\Java\jre1.8.0_192\bin>

> C:\Program Files\Java\jre1.8.0_192>clist -l |find "jre8"
> jre8 8.0.191.20181114
> 
> C:\Program Files\Java\jre1.8.0_192>

(jre1.8.0_192 went poof!)

https://chocolatey.org/packages/openhab is one of my packages that relies on JAVA_HOME to be set correctly to work. I've added code to simply check and warn about JAVA_HOME not being set right since I find it wrong after every upgrade:

> if (!($env:JAVA_HOME)) {
>     Write-Warning "  ** JAVA_HOME enviromental variable not set. You should set this."
>    } else {
>      if (!(Test-Path $env:JAVA_HOME)){
>          Write-Warning "  ** JAVA_HOME is set to $env:JAVA_HOME but $env:JAVA_HOME does not exist."
>         }
>   }

I'm very surprised the native installer doesn't update this automatically. I'm reaching out to you in hope you will consider checking and fixing JAVA_HOME via the install script.

**Comment by proudcanadianeh** [comment]
I have had requests for this before, and I am honestly torn about if I should do anything about it. I am hesitant to start messing with the JAVA_HOME variable manually when the installer doesn't do it automatically. I am especially hesitant because if anyone has that variable pointing to a specific version installed and I overwrite it, I could be breaking local applications. 

It seems like either way this can cause huge issues, and if thats the case then following the default behaviour with the package is my best bet.

**Comment by bcurran3** [comment]
I understand your concerns.

May I suggest some sort of conditional compromise action? i.e. if JAVA_HOME is NOT set, then to set it?

Some research might shed light on other options; i.e maybe JAVA_HOME points to a different vendor's version of Java and shouldn't be touched. This could also lead to verifying that version is actually installed, and if not, then change the JAVA_HOME to the location of the new install. There's probably a bunch of scenarios to explore. But maybe we can start moving forward in baby steps?

**Comment by RedBaron2** [comment]
@proudcanadianeh @bcurran3 
According to the documentation for the [JAVA_HOME variable](https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/).  This is only to be set for JDK and not for JRE. The JRE installer is doing the correct install by skipping and not setting the JAVA_HOME variable.

**Comment by bcurran3** [comment]
Thanks. 

I guess the JAVA_HOME variable is never auto-created.

Weird that some programs expect it though; i.e. OpenHAB. I'm going to bring this up with them that they should look for an alternate way to find where Java is installed and not rely on the variable.
