### ISSUE TITLE
switches for `javaruntime` package do not work

### ISSUE THREAD

**Issue by DJCrashdummy** [proudcanadianeh/ChocoPackages#32]
it seems to me, that the `javaruntime` metapackage is not passing the arguments like `packageParameters="/exclude:32"` to the `jre8` package.

is this intended? is something like this not possible with chocolatey? is this a bug at the packages/chocolatey? or do i miss something completely different?

**Comment by RedBaron2** [comment]
@DJCrashdummy 
The meta packages currently for chocolatey only place dependency on a package. They do not have chocolateyinstall files.

Simply put without any install logic in the package no amount of package parameters will be read, passed, or executed when installing from meta packages.

**Comment by DJCrashdummy** [comment]
<s>@RedBaron2 thanks for clarification.

it's a pity that this isn't possible with chocolatey (for now). IMHO it would make sense to have such a feature or even simply pass through the switches (perhaps by default) if there is just one dependency, since it is very likely that it is a transitional/virtual package or similar.
...this also explains why switches do not work with some packages (`xyz`) which have one dependency (`xyz.install`).</s>

**Comment by DJCrashdummy** [comment]
i was about opening a bug report resp. feature request, when i found https://github.com/chocolatey/choco/issues/839.

so @RedBaron2 it seems to be indeed **possible**, but just **not by default** even if there is just one dependency as in the case of transitional/virtual packages.

https://docs.chocolatey.org/en-us/choco/commands/install#options-and-switches
```
--paramsglobal, --params-global, --packageparametersglobal, --package-parameters-global, --applyparamstodependencies, --apply-params-to-dependencies, --apply-package-parameters-to-dependencies
Apply Package Parameters To Dependencies  - Should package parameters be 
  applied to dependent packages? Defaults to false.
```
