### ISSUE TITLE
Version 8 Update 371

### ISSUE THREAD

**Issue by davidenco** [proudcanadianeh/ChocoPackages#35]
JRE Version 8 Update 371 has been released.

**Comment by proudcanadianeh** [comment]
Thanks for the heads up! I am planning on updating the package this weekend and pushing it MondaySent from my iPhoneOn Apr 28, 2023, at 2:18 AM, davidenco ***@***.***> wrote:﻿
JRE Version 8 Update 371 has been released.

**Comment by ralfbosz** [comment]
And JRE Version 8 Update 381 is out now!

**Comment by proudcanadianeh** [comment]
Thanks for the heads up! Will get this updated and pushed either Monday or TuesdaySent from my iPhoneOn Jul 25, 2023, at 11:31 PM, Ralf Bosz ***@***.***> wrote:﻿
And JRE Version 8 Update 381 is out now!

**Comment by asheroto** [comment]
Has this package been abandoned?

**Comment by proudcanadianeh** [comment]
> Has this package been abandoned?

Nope, I am just terrible at using Github. I regularly update and push versions to Chocolatey.

**Comment by asheroto** [comment]
Gotcha. It looks like 431 was out October 15, 2024.

https://www.java.com/en/download/

Do you have an [AU package](https://docs.chocolatey.org/en-us/create/automatic-packages/) for this so you won't have to keep manually updating it?

**Comment by proudcanadianeh** [comment]
That version was pushed last month. Are you having issues downloading it?

**Comment by asheroto** [comment]
Sorry, I should have been more descriptive. The Choco package is reporting version 411, last updated in April. I don't see any pending Choco packages in Version History. 431 appears to be the latest.

https://community.chocolatey.org/packages/javaruntime

**Comment by proudcanadianeh** [comment]
Ohhhhhhh I see now. That just points to the actual JRE8 package that is up to date.

**Comment by proudcanadianeh** [comment]
I just pushed an updated version of the javaruntime package so the version matches, but rest assured if you installed that it would have used the up to date JRE8 package.

**Comment by asheroto** [comment]
Thanks for your time!
