### ISSUE TITLE
Install JRE8 Checksum issues

### ISSUE THREAD

**Issue by rondelward** [proudcanadianeh/ChocoPackages#4]
I'm running into an issue with the checksum for the 32bit version of JRE8 while running "choco install jre8". 

The error looks like this

> jre8 v8.0.121
Searching if new version exists...
Write-Error : jre8 did not finish successfully. Boo to the chocolatey gods!
-----------------------
>[ERROR] Checksum for 'C:\Users\JKAZAN~1\AppData\Local\Temp\chocolatey\jre8\jre8Install.exe' did not meet '13D5ED94FE40D
9403D5D25B1EF46593DC7F96993DF735EA36A32DB3DC8ED8EC7' for checksum type 'md5'.
-----------------------
>At C:\ProgramData\chocolatey\chocolateyinstall\helpers\functions\Write-ChocolateyFailure.ps1:30 char:3
>+   Write-Error $errorMessage
>+   ~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Error

>Write-Error : Package 'jre8 v8.0.121' did not install successfully: Checksum for 'C:\Users\JKAZAN~1\AppData\Local\Temp\
chocolatey\jre8\jre8Install.exe' did not meet '13D5ED94FE40D9403D5D25B1EF46593DC7F96993DF735EA36A32DB3DC8ED8EC7' for ch
ecksum type 'md5'.
>At C:\ProgramData\chocolatey\chocolateyinstall\functions\Chocolatey-NuGet.ps1:90 char:17
+                 Write-Error "Package `'$installedPackageName v$installedPackageV ...
+ >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by proudcanadianeh** [comment]
The issue is you are using an out of date version of Chocolatey, you have to update that for it to recognise the proper checksums.
